Fix typo: change 'nr_mixer' to 'nr_mixers' in permutation.c
- Fixed undeclared variable 'nr_mixer' in generate_chase_mixer function
- Changed to 'nr_mixers' as suggested by compiler
- Resolves compilation error in permutation.c:99