Update the undeclared variable error caused due to nr_mixer argument
We are facing the following error while executing the benchmark

```
permutation.c:99:7: error: 'nr_mixer' undeclared (first use in this function); did you mean 'nr_mixers'?
   99 |   if (nr_mixer > 1) {
      |       ^~~~~~~~
      |       nr_mixers
```